# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sword', models.CharField(max_length=4)),
                ('pinyin', models.CharField(default='', max_length=4)),
                ('word_class', models.CharField(max_length=10)),
                ('meaning', models.CharField(max_length=100)),
                ('sample', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SWordTest1Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=10)),
                ('choice_txt', models.CharField(max_length=100)),
                ('is_correct', models.IntegerField(default=0)),
                ('sword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_word.SWord')),
            ],
        ),
    ]
