# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleSyllable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('classical', models.CharField(max_length=100)),
                ('current', models.CharField(max_length=100)),
                ('sample', models.CharField(max_length=120)),
                ('translation', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleSyllableAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(verbose_name='date accessed')),
                ('doublesyllable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubleSyllable.DoubleSyllable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleSyllableTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(verbose_name='test accessed')),
                ('test_result', models.IntegerField(default=0)),
                ('doublesyllable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubleSyllable.DoubleSyllable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
