# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoubleSyllable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleSyllableTestChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_txt', models.CharField(max_length=100)),
                ('is_correct', models.IntegerField(default=0)),
                ('doublesyllable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubleSyllable.DoubleSyllable')),
            ],
        ),
    ]
